// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('Testi').service('WoWservice', function($resource) {
    return $resource('http://eu.battle.net/api/wow/character/:realm/:character', {
      realm: '@realm',
      character: '@character'
    }, {
      get: {
        method: "GET",
        isArray: false
      }
    });
  });

}).call(this);
